"""empty message

Revision ID: d8a06542cffc
Revises: e9a564734d60
Create Date: 2016-10-28 20:47:42.925261

"""

# revision identifiers, used by Alembic.
revision = 'd8a06542cffc'
down_revision = 'e9a564734d60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('description', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'description')
    ### end Alembic commands ###
